### ISSUE TITLE
Unable to edit beginning of input field

### ISSUE THREAD

**Issue by mobitar** [sn-extensions/simple-task-editor#9]
I believe this is a recent regression due to the auto-saving input field (cc @bryvin). If you type "Foo" in the new task input field, then move the cursor to the beginning of the input, then type another letter, it will add that letter, but then immediately move the cursor to the end of the input.

**Comment by bryvin** [comment]
Oh yeah it will be actually.. that happens because since that field is saved with the note to keep it's state the field value is built off the state.

I still don't know that much about React but can you think of an easy way to fix that? Maybe need to de-couple the value property from the state and only set the value once when it's initialized.

**Comment by mobitar** [comment]
Not sure without being in there, but every time you set state, it will re-render. It could be the input is getting destroyed and re-added every time. Maybe setting the `key` prop can help so that it's reused. But updating state on text input is a common paradigm, so not sure why it's causing problems here.

**Comment by bryvin** [comment]
Alright I'll mess around with this a bit here today then.

**Comment by bryvin** [comment]
Just submitted a PR. Apparently just using the props as the value instead of building the form field on the state itself corrected this issue.

**Comment by mobitar** [comment]
Awesome, thanks!

**Comment by alandooz** [comment]
I think this is fixed based on that PR.
